# Source: ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: console-https-secret-create
  namespace: @@NAME_NS@@
spec:
  template:
    metadata:
      name: console-https-secret-create
    spec:
      containers:
        - name: create
          image: docker.io/jettech/kube-webhook-certgen:v1.3.0
          imagePullPolicy: IfNotPresent
          args:
            - create
            - --host=console,console.$(POD_NAMESPACE).svc
            - --namespace=$(POD_NAMESPACE)
            - --secret-name=console-https-scret
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            limits:
              cpu: '1'
              memory: '1Gi'                  
      restartPolicy: OnFailure
      serviceAccountName: @@NAME_NS@@-admin
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
