apiVersion: v1
kind: Service
metadata:
  name: console-np
  namespace: @@NAME_NS@@
spec:
  type: NodePort
  ports:
  - name: "https"
    port: 80
    targetPort: 6443
    nodePort: 31305
  selector:
    app: console   
    hypercloud: ui