apiVersion: v1
kind: Service
metadata:
  name: console-lb
  namespace: @@NAME_NS@@
spec:
  type: LoadBalancer
  ports:
  - name: "https-lb"
    port: 443
    targetPort: 6443
  selector:
    app: console   
    hypercloud: ui