proxyInfo: 
  - name: show
    server: "http://192.168.8.62:9002/"
    rule: "Host(`console`) && PathPrefix(`/console/`)"
    path: "/console/"
  - name: cpd
    server: "http://cpdch.org/"
    rule: "Host(`cpdch.org`) && PathPrefix(`/test/`)"
    # host: "cpdch.org"
    path: "/test/"
  - name: naver
    server: "https://www.naver.com/"
    rule: "Host(`naver.com`) && PathPrefix(`/naver/`)"
    path: "/naver/"
