routers:
  daum:
    server: https://www.daum.com/
    rule: Host(`daum.com`) && PathPrefix(`/daum/`)
    path: /daum/
  google:
    server: https://google.com/
    rule: Host(`google.com`) && PathPrefix(`/google/`)
    path: /google/
  naver:
    server: https://www.naver.com/
    rule: Host(`naver.com`) && PathPrefix(`/naver/`)
    path: /naver/
  show:
    server: http://192.168.8.62:9002/
    rule: Host(`console`) && PathPrefix(`/console/`)
    path: /console/
