apiVersion: v1
kind: Service
metadata:
  name: console-lb
  namespace: console-system
spec:
  type: LoadBalancer
  ports:
  - name: "https-lb"
    port: 31305
    targetPort: 6443
  selector:
    app: console   
    hypercloud: ui
